name: aussedthick
channels:
  - conda-forge
dependencies:
  - python=3.9
  - openmpi
  - fortran-compiler
  - ipykernel
  - pygmt
  - nbconvert
  - geopandas
  - requests-html
  - selenium
  - webdriver-manager
