name: main_ci

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: aussedthick
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - run: |
          conda info
          conda list
          cd $GITHUB_WORKSPACE/hiperseis
          pip install .
        env:
            FFLAGS: "${FFLAGS} -fallow-argument-mismatch"
